### ISSUE TITLE
Blog demo app fails

### ISSUE THREAD

**Issue by jogilder** [Pylons/substanced#250]
When I try and create a new blog entry in the demo I got:

"ConfigurationError: Unsatisfied after dependencies: upload"

The blog entry is created as you can see it listed as an item under root. However you can't click on it and go to manage_main view. Seems to fall over when trying to assign tab order.

**Comment by cguardia** [comment]
Thanks for the feedback. I don't get that error, so we need more details. Was this from the pypi download or are you running from a git checkout?

**Comment by jogilder** [comment]
Hi, I get the same error whether I run from the pypi or the git checkout. I am running on a virtualbox install using python 2.7.8 in a virtual environment. I am running on waitress server in develop mode. I selected all of the defaults on the add a blog view.
Below is the error output:

```

2015-06-17 09:41:03,458 ERROR [waitress][Dummy-2] Exception when serving /manage/hello/@@properties
Traceback (most recent call last):
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/channel.py", line 337, in service
    task.service()
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/task.py", line 173, in service
    self.execute()
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/router.py", line 223, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/router.py", line 198, in invoke_subrequest
    response = handle_request(request)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid_tm-0.12-py2.7.egg/pyramid_tm/__init__.py", line 99, in tm_tween
    reraise(*exc_info)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid_tm-0.12-py2.7.egg/pyramid_tm/__init__.py", line 80, in tm_tween
    response = handler(request)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/router.py", line 145, in handle_request
    view_name
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/view.py", line 527, in _call_view
    response = view_callable(context, request)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/config/views.py", line 327, in attr_view
    return view(context, request)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/config/views.py", line 303, in predicate_wrapper
    return view(context, request)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/config/views.py", line 243, in _secured_view
    return view(context, request)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/config/views.py", line 376, in rendered_view
    context)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/renderers.py", line 443, in render_view
    return self.render_to_response(response, system, request=request)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/renderers.py", line 466, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/renderers.py", line 462, in render
    result = renderer(value, system_values)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid_chameleon-0.3-py2.7.egg/pyramid_chameleon/zpt.py", line 47, in __call__
    result = self.template(**system)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 124, in __call__
    return self.render(**kwargs)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "propertysheets_19d305535231b47b41e4777a62463e69.py", line 555, in render
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 262, in include
    self._render(*args, **kwargs)
  File "master_624a20acfbe1971e2544258f4a10e605.py", line 1526, in render
  File "master_624a20acfbe1971e2544258f4a10e605.py", line 1097, in render_main
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/substanced-1.0a1-py2.7.egg/substanced/sdi/__init__.py", line 526, in mgmt_views
    return self.sdi_mgmt_views(context, self.request)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/substanced-1.0a1-py2.7.egg/substanced/sdi/__init__.py", line 391, in sdi_mgmt_views
    x[1] for x in tsorter.sorted() if x[0] not in (CENTER1, CENTER2)
  File "/home/bodl-dm-svc/sites/bodl-dm-svc/lib/python2.7/site-packages/pyramid-1.6a1-py2.7.egg/pyramid/util.py", line 477, in sorted
    % (', '.join(sorted(self.req_after - has_after)))
ConfigurationError: Unsatisfied after dependencies: upload

 - Expression: "request.sdiapi.mgmt_views(context)"
 - Filename:   ... 1.0a1-py2.7.egg/substanced/sdi/views/templates/master.pt
 - Location:   (line 114: col 33)
 - Source:     ... al:define="tabs request.sdiapi.mgmt_views(context)"
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  js_links: <list - at 0x7f7c16770830>
               renderer_name: templates/propertysheets.pt
               form: <form\n  id="deform"\n  method="POST"\n  enctype="mul...
               renderer_info: <RendererHelper - at 0x7f7c169e7090>
               repeat: {...} (0)
               req: <Request - at 0x7f7c243f2690>
               request: <Request - at 0x7f7c243f2690>
               css_links: <list - at 0x7f7c16770758>
               context: <BlogEntry hello at 0x7f7c18efe938>
               view: <PropertySheetsView - at 0x7f7c16b0d550>
```

**Comment by cguardia** [comment]
This is a confirmed problem with the 1.0a1 release, but it is fixed on master and will be fixed in the next alpha release.

If you tried 1.0a1 and then master on the same virtual env, make sure you remove the 1.0a1 egg from lib/site-packages and run setup.py develop in the substanced checkout dir.
