### ISSUE TITLE
Tests failing in clean checkout

### ISSUE THREAD

**Issue by Themanwithoutaplan** [Pylons/substanced#261]
Just forked and checked out Substance D ready for some changes and I'm getting a test failure. Not sure what might causing it: broken test/code or a change in nose. Will investigate.

```
ERROR: test_register_workflow_no_such_content_type (substanced.workflow.tests.test_workflow.register_workflowTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/charlieclark/Projects/Pyramid/substanced/substanced/workflow/tests/test_workflow.py", line 1018, in test_register_workflow_no_such_content_type
    self.config.registry.content.exists.assert_call('Foobar')
  File "/Users/charlieclark/Projects/Pyramid/substanced/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 721, in __getattr__
    raise AttributeError(name)
AttributeError: assert_call
```

**Comment by Themanwithoutaplan** [comment]
Bug is related to mock but already fixed by Domen.
